[package]
name = "block-value-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19.0"
clap = { version = "4.5.7", features = ["derive"] }
